FROM apache/airflow:2.9.3-python3.11

USER root
RUN mkdir -p /opt/airflow/logs && chown -R 50000:0 /opt/airflow/logs
USER airflow

COPY requirements-airflow.txt /tmp/requirements.txt
RUN pip install --no-cache-dir -r /tmp/requirements.txt
